export const RARITIES = {
  common: {
    label: 'Common',
    weight: 60,
    price: [1, 3],
    color: '#91ab83',
    window: 30,
    speed: 0.75,
  },
  uncommon: {
    label: 'Uncommon',
    weight: 25,
    price: [4, 7],
    color: '#60b5ba',
    window: 26,
    speed: 1,
  },
  rare: {
    label: 'Rare',
    weight: 10,
    price: [10, 15],
    color: '#819ee1',
    window: 22,
    speed: 1.2,
  },
  epic: {
    label: 'Epic',
    weight: 4,
    price: [25, 40],
    color: '#bd92d6',
    window: 18,
    speed: 1.45,
  },
  legendary: {
    label: 'Legendary',
    weight: 0.99,
    price: [75, 75],
    color: '#eec477',
    window: 15,
    speed: 1.75,
  },
  mythic: {
    label: 'Mythic',
    weight: 0.01,
    price: [200, 200],
    color: '#e8a6d7',
    window: 12,
    speed: 2,
  },
};
export const FISH = [
  [
    'lumoss',
    'Lumoss',
    'common',
    '#8dbf76',
    'A drifting patch of moss. Its little leaves glow whenever someone has a new idea.',
  ],
  [
    'pebblin',
    'Pebblin',
    'common',
    '#b6aaa1',
    'A skipping stone that forgot to stop swimming. Quartz grows where its tail should be.',
  ],
  [
    'teacup',
    'Teacup Fin',
    'common',
    '#dbbba4',
    'A tiny porcelain wanderer carrying the last warm sip of a very old afternoon.',
  ],
  [
    'ribbon',
    'Ribbon Ray',
    'common',
    '#d88eac',
    'It ties the currents into little bows. Nobody knows what the ocean is celebrating.',
  ],
  [
    'lantern',
    'Lantern Guppy',
    'common',
    '#efc879',
    'A moving lighthouse for creatures smaller than a grain of sand.',
  ],
  [
    'inkwhisk',
    'Inkwhisk',
    'common',
    '#8a96b5',
    'A living ink spill that paints new paths through the water with its brush whiskers.',
  ],
  [
    'clocktail',
    'Clocktail',
    'uncommon',
    '#d9b873',
    'Every turn of its clockwork tail makes a lost second appear somewhere else.',
  ],
  [
    'prism',
    'Prism Puff',
    'uncommon',
    '#91d0d2',
    'A floating prism that can split moonlight into colors no painter has named.',
  ],
  [
    'cloud',
    'Cloud Koi',
    'uncommon',
    '#c2dce5',
    'A pocket-sized weather system. Its rain falls upward on especially happy days.',
  ],
  [
    'ember',
    'Emberjaw',
    'uncommon',
    '#e79869',
    'A coal from a forgotten campfire. The water around it is always pleasantly warm.',
  ],
  [
    'origami',
    'Origami Sail',
    'uncommon',
    '#d6dbc0',
    'A paper wish folded into a creature. Somehow, it has never gotten wet.',
  ],
  [
    'moonveil',
    'Moonveil',
    'rare',
    '#c8c4f0',
    'A crescent moon wrapped in a ribbon of silver tide. It only remembers dreams.',
  ],
  [
    'circuit',
    'Circuit Eel',
    'rare',
    '#82d4b4',
    'A curious electrical thought taking the long way through the lake.',
  ],
  [
    'glassgarden',
    'Glassgarden',
    'rare',
    '#a1d4ae',
    'A miniature forest in a traveling glass terrarium, rooted in a drop of water.',
  ],
  [
    'comet',
    'Comet Skipper',
    'rare',
    '#edba8f',
    'It fell from a constellation and decided this little lake was a lovely place to stay.',
  ],
  [
    'cathedral',
    'Cathedral Ray',
    'epic',
    '#c8a3db',
    'Its stained-glass wings tell the story of a city that sank before it was built.',
  ],
  [
    'dreamweaver',
    'Dreamweaver',
    'epic',
    '#b7b1e9',
    'A spool of sleeping thoughts. Its trailing threads become dreams at the shore.',
  ],
  [
    'abyssal',
    'Abyssal Crown',
    'epic',
    '#9fa4dd',
    'A quiet monarch whose crown is made of stars that never reached the sky.',
  ],
  [
    'aurora',
    'Aurora Leviathan',
    'legendary',
    '#9de6d2',
    'A river dragon wearing the northern lights. The whole lake holds its breath as it passes.',
  ],
  [
    'unwritten',
    'The Unwritten',
    'mythic',
    '#edb2e2',
    'Something from between the pages of reality. It has no true shape, only possibilities.',
  ],
].map(([id, name, rarity, color, lore], index) => ({
  id,
  name,
  rarity,
  color,
  lore,
  index,
}));
export const RODS = [
  {
    id: 'twig',
    name: 'Twigline',
    price: 0,
    luck: 0,
    color: '#a1b57d',
    description: 'A little branch. A whole world of possibility.',
  },
  {
    id: 'moon',
    name: 'Moonthread',
    price: 40,
    luck: 0.15,
    color: '#99bfdc',
    description: 'Silver thread, woven from the quiet side of the moon.',
  },
  {
    id: 'astral',
    name: 'Astralhook',
    price: 150,
    luck: 0.4,
    color: '#cfaae2',
    description: 'A crystal hook that tugs gently at the edges of reality.',
  },
];
export const getFish = (id) => FISH.find((f) => f.id === id);
